class LighthouseError(Exception):
    """
    An error generated by Lighthouse.
    """
    def __init__(self, *args, **kwargs):
        super(LighthouseError, self).__init__(*args, **kwargs)

class CoverageParseError(LighthouseError):
    """
    An error generated by the CoverageReader.
    """
    def __init__(self, filepath, tracebacks):
        super(CoverageParseError, self).__init__("Failed to parse coverage file")
        self.filepath = filepath
        self.tracebacks = tracebacks

class CoverageExtractionError(LighthouseError):
    """
    An error generated when extracting data from a coverage file fails.
    """
    pass
